version: '3'
services:
  minio:
    image: 'minio/minio'
    environment:
      MINIO_ACCESS_KEY: 'testkey'
      MINIO_SECRET_KEY: 'testsecret'
    ports:
      - '9000:9000'
    command: '--compat server /data'
  mc:
    image: 'minio/mc'
    environment:
      MINIO_ACCESS_KEY: 'testkey'
      MINIO_SECRET_KEY: 'testsecret'
    volumes:
      - './dev-data.sh:/dev-data.sh'
    entrypoint: '/dev-data.sh'
    depends_on:
      - minio
